$(document).on 'turbolinks:load', ->
  show_error = undefined
  stripeResponseHandler = undefined
  submitHandler = undefined

  submitHandler = (event) ->
    $form = $(event.target)
    $form.find('input[type=submit]').prop 'disabled', true
    #If Stripe was initialized correctly this will create a token using the credit card info
    if Stripe
      Stripe.card.createToken $form, stripeResponseHandler
    else
      show_error 'Failed to load credit card processing functionality. Please reload this page in your browser.'
    false

  $('.cc_form').on 'submit', submitHandler

  stripeResponseHandler = (status, response) ->
    token = undefined
    $form = undefined
    $form = $('.cc_form')
    if response.error
      console.log response.error.message
      show_error response.error.message
      $form.find('input[type=submit]').prop 'disabled', false
    else
      token = response.id
      $form.append $('<input type="hidden" name="payment[token]" />').val(token)
      $('[data-stripe=number]').remove()
      $('[data-stripe=cvv]').remove()
      $('[data-stripe=exp-year]').remove()
      $('[data-stripe=exp-month]').remove()
      $('[data-stripe=label]').remove()
      $form.get(0).submit()
    false

  show_error = (message) ->
    if $('#flash-messages').size() < 1
      $('div.container.main div:first').prepend '<div id=\'flash-messages\'></div>'
    $('#flash-messages').html '<div class="alert alert-warning"><a class="close" data-dismiss="alert">×</a><div id="flash_alert">' + message + '</div></div>'
    $('.alert').delay(5000).fadeOut 3000
    false

  return

# ---
# generated by js2coffee 2.2.0